---
- hosts: all
  become: yes
  gather_facts: true
  tasks:
      - name: install NTP for Debian
        apt:
           name: ntp
           state: present
        when: ansible_distribution == 'Debian'   
 
      - name: install NTP for CentOS
        yum:
           name: ntp
           state: present
        when: ansible_distribution == 'CentOS'
        
      - name: start service Debian
        service: 
           name: ntp
           state: started
        when: ansible_distribution == 'Debian'
        
      - name: start service CentOS
        service: 
           name: ntpd
           state: started
        when: ansible_distribution == 'CentOS'
        
      - name: set timezone Europe/London
        timezone:
           name: Europe/London