---
- hosts: all
  become: yes
  tasks:
      - name: install NTP
        apt:
           name: ntp
           state: present
      - name: start service
        service: 
           name: ntp
           state: started